[스택,큐,덱] 3월 11일 1차 제출
Altu-Bitu-2/Algorithm-Altu-Bitu2-assignment pull request #4
Opened 2022-03-16 23:22 UTC by yyeonzu

#### 내용 & 질문
> 1213: 코드는 맞았다고 생각하는데 결과값 출력이 안됩니다..! 무엇이 잘못된건지 못찾겠습니다.
2108: 최빈값 함수를 아직 만들지 못했습니다. 

#### <기존 제출>
> 1213, 2108, 2841, 11866, 18115

#### <추가 제출>
>

2022-03-17 08:25 UTC, mkwkw requested changes
스택, 큐, 덱 활용해서 문제 잘 풀어주셨습니다. 2108번 제외하고 코멘트 작성하였습니다!
선택 문제 2문제 확인되었습니다:)

수정하시고 오른쪽 상단의 re-request review 버튼 눌러주세요~

2022-03-17 08:25 UTC, mkwkw commented on [스택,큐,덱] 3월 11일/11866.cpp
> +}
p2. 연산하는 부분을 함수화하는 것이 좋아요! main함수에서는 입출력에 관한 코드 위주로 작성하고 연산하는 코드는 함수로 따로 빼주는 것이 좋습니다:)

2022-03-17 08:25 UTC, mkwkw commented on [스택,큐,덱] 3월 11일/1213.cpp
> +
p1. 일단 입력받은 s를 분석하는 부분의 코드가 없습니다! 바로 홀수, 짝수로 넘어가네요.

2022-03-17 08:25 UTC, mkwkw commented on [스택,큐,덱] 3월 11일/18115.cpp
> +}
p2. 연산하는 과정은 함수로 작성하는 것이 좋을 것 같아요!

2022-03-17 08:25 UTC, mkwkw commented on [스택,큐,덱] 3월 11일/2108.cpp
> +
p2. 전역변수는 사용하지 않는 것이 좋아요. 함수에는 매개변수로 넘겨주면 됩니다~

2022-03-17 08:25 UTC, mkwkw commented on [스택,큐,덱] 3월 11일/2108.cpp
> +                              // 이 문제 뿐만 아니라 다른 문제에서도 그렇습니다.. 언제 for문을 사용하고 언제 while을 사용하나요?
for문은 반복횟수가 정해져 있거나 배열을 탐색해서 인덱스로 접근할 때, 반복할 때마다 변수를 초기화해야할 때 주로 사용합니다.
while문은 반복을 계속 하다가 특정조건에서 탈출해야할 경우에 주로 사용합니다.

오류가 나는 이유는 잘 모르겠네요..

2022-03-17 08:25 UTC, mkwkw commented on [스택,큐,덱] 3월 11일/2841.cpp
> +        }
p1. stack에서 pop할 때, stack이 비어있지 않은 상태인지 확인하고 pop하는 것이 중요해요! stack이 빈 상태에서 pop하면 오류가 발생합니다.

2022-03-17 08:25 UTC, mkwkw commented on [스택,큐,덱] 3월 11일/2841.cpp
> +        cnt++;
p1. stack에 push할 조건을 따로 만드는 것이 좋아요. 이렇게 되면 어느조건에서 push가 되는지 알기 어렵습니다.

2022-03-17 08:25 UTC, mkwkw commented on [스택,큐,덱] 3월 11일/2841.cpp
> +            break;
p1. 여기서 break를 하면 반복문이 n번 다 돌아가지 못하고 중간에 중단되고 프로그램이 종료됩니다.

2022-03-17 08:25 UTC, mkwkw commented on [스택,큐,덱] 3월 11일/2841.cpp
> +            break;
p1. 여기서 break를 하면 반복문이 n번 다 돌아가지 못하고 중간에 중단되고 프로그램이 종료됩니다. 
그리고 연산이 필요없는 조건이라면 굳이 작성할 필요가 없어요!

2022-03-17 14:49 UTC, yyeonzu commented on [스택,큐,덱] 3월 11일/2841.cpp
> +            break;
안녕하세요! 혹시 코드 수정한 게 보이실까요..? 지금 깃허브 데스크탑에서 커밋한게 푸시가 안되고 있는 상황이라서요 ... 😥 어째서인지 pr 메세지도 수정이 안되네요... 여기에 코멘트 남기도록 하겠습니다..!

2841번 문제 코드는 맞다고 생각하는데, 컴파일하면 Segmentation fault (core dumped) 오류가 발생합니다. 구글링 해보니 메모리의 문제인 것 같은데.. 어떤 부분을 어떻게 수정해야할지.. 디버깅은 어떻게 해야할지 모르겠어서 질문 드립니다 ㅠㅠ

이외의 문제들은 p1, p2 반영하여 전부 수정했습니다!

2022-03-18 05:39 UTC, mkwkw requested changes
깃허브 오류 때문인지 코드 수정하신 게 보이지 않습니다! segmentation error는 stack에 조작을 가하는 과정에서 발생한 것 같은데 코드 수정하시면 그때 다시 보도록 하겠습니다~ 수정 반영하시고 다시 저 불러주세요~

2022-03-18 10:59 UTC, yyeonzu commented
코드 수정했습니다~!

2022-03-18 12:37 UTC, mkwkw requested changes
전체적으로 잘 수정해주셨습니다:) 2841번에 코멘트 작성하였습니다:)
수정하시고 re-request review 버튼으로 저 다시 호출해주세요~

2022-03-18 12:37 UTC, mkwkw commented on [스택,큐,덱] 3월 11일/2841.cpp
> +}
p1.  수정해야할 부분에 대해 정리해드립니다!
조건문 반복문 순서: top의 값이 연주해야하는 값보다 높을 때 - 카드를 다 빼고 (while) 스택의 top이 프렛보다 작은지 확인(if문)한다. 
지금 stack이 비었을 때, 첫번 째 if 문 프렛 번호를 넣고, while문이 돌아가서 코드 흐름이 꼬인 상태입니다.
그리고 스택이 비었는지를 먼저 체크하고 top과 k의 값을 비교해주어야합니다. 이 부분에서 segmentation fault가 발생했던 것입니다. 지금은 스택이 빈 상태일 때에도 top값을 확인하므로 오류가 발생합니다! 결론적으로 empty를 먼저 체크하고 top값을 확인해야합니다!

2022-03-18 13:35 UTC, yyeonzu commented
2841 수정 완료했습니다! empty 조건때문에 카운트가 안되는 값이 있어서, 스택이 비어있는 경우와 top의 값이 연주하는 음보다 낮을 때를 하나로 합쳐 조건문으로 만들었습니다~! 
친절하고 자세한 답변 항상 감사합니다 튜터님 🥰

2022-03-18 13:49 UTC, mkwkw approved these changes
최종적으로 필수 2문제, 선택 3문제 확인되었습니다! 머지하셔도 됩니다~
열심히 활동에 참여하시고 과제 수행해주셔서 감사합니다:)
좋은 말씀해주셔서 힘이 나네요~~

2022-03-18 14:01 UTC, merged